export const FETCH_GAMES = 'FETCH_GAMES';
export const LOADING_GAMES = 'LOADING_GAMES';
export const GET_GAME_DETAILS = 'GET_GAME_DETAILS';
export const LOADING_GAME_DETAILS = 'LOADING_GAME_DETAILS';
export const FETCH_SEARCHED_GAMES = 'FETCH_SEARCHED_GAMES';
export const SEARCHING_GAMES = 'SEARCHING_GAMES';
export const CLEAR_SEARCHED_GAMES = 'CLEAR_SEARCHED_GAMES';
