export const FETCH_GAMES = "FETCH_GAMES";
export const LOADING_GAMES = "LOADING_GAMES";
export const GET_GAME_DETAILS = "GET_GAME_DETAILS";
export const LOADING_GAME_DETAILS = "LOADING_GAME_DETAILS";
